name: CI/CD - Bottle Store

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: repository checkout
        uses: actions/checkout@v3

      - name: Configure JDK 21
        uses: actions/setup-java@v3
        with:
          distribuition: 'temurin'
          java-version:

      - name: Build & tests with Maven
        run: mvn clean verify

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Build Docker Image
        run: docker build -t eltonmessias/bottle-store:latest .

      - name: Push to Docker Hub
        run: docker push eltonmessias/bottle-store


